version: '2.3'
services:
  augur-code:
    image: augur/augur-code
    container_name: augur-code
    network_mode: "host"
    command: "../harness/${CMD_PARAMS}"
    volumes:
      - ./input:/app/input
      - ./output:/app/output
